version: '3.9'

networks:
  net_databases:
    driver: bridge

volumes:
  mongodb_data:
    driver: local

services:
  mongodb:
    container_name: mongodb
    build: ./mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - net_databases
