version: '3.9'

networks:
  net_databases:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  pg_data:
    driver: local
  # mariadb_data:
  #   driver: local

services:
  mongodb:
    container_name: mongodb
    build: ./mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: 27017
    volumes:
      - mongodb_data:/data/db
    networks:
      - net_databases

  postgres:
    container_name: postgres
    build: ./postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret
    networks:
      - net_databases

  # mariadb:
  #   container_name: mariadb
  #   build: ./mongo
  #   image: mariadb
  #   restart: always
  #   ports:
  #     - "43306:3306"
  #   environment:
  #     MARIADB_ROOT_PASSWORD: "${ENV_DB_PASSWORD}"
  #   volumes:
  #     - mariadb_data:/var/lib/mysql
  #   networks:
  #     - net_databases
